easy_admin:
  entities:
    Post:
      class: Blog\Entity\Post
      controller: Blog\Controller\PostController
      form:

        fields:
          - { property: 'title', label: 'Title', type: 'text' }
          - { property: 'date', label: 'Date', type: 'date' }
          - { property: 'categories', label: 'Categories', type: 'entity', type_options: { multiple: true }}
          - { property: 'deleted', label: 'Deleted', type: 'date'}

      list:
        fields:
          - { property: 'id' }
          - { property: 'title' }
          - { property: 'categories' }
          - { property: 'slug', label: 'Slug', type: 'text'}
          - { property: 'comments' }
          - { property: 'created' }
          - { property: 'updated' }