easy_admin:
  entities:
    User:
      class: Blog\Entity\User
      controller: Blog\Controller\UserController
      form:

        fields:
          - { property: 'email', label: 'Email', type: 'email' }
          - { property: 'password', label: 'Password', type: 'password' }
          - { property: 'isActive', label: 'Is Active', type: 'checkbox' }
          - { property: 'roles', label: 'Roles', type: 'choice', type_options: {expanded: true, multiple: true, choices: {'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' }}}

      list:
        fields:
          - { property: 'id' }
          - { property: 'email' }
          - { property: 'isActive' }
          - { property: 'roles' }
          - { property: 'created' }
          - { property: 'updated' }
